model_output_directory: models
data_directory: data
source_file: train_daev_model.py
arguments: ${dataset}, ${output_directory}
architechture: nn/conv/dave2.py
learning_rate: 0.05,
num_epochs: 10000
decay: 0.01/num_epochs
momentum: 0.9
nesterov: True